### ISSUE TITLE
Crashes when hovering over fluid in Indrev machines 

### ISSUE THREAD

**Issue by Justsnoopy30** [kvverti/colormatic#65]
Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:883)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:65)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3610.method_15759()" because "state" is null
	at io.github.kvverti.colormatic.iface.ColormaticFluidRenderHandler.getFluidColor(ColormaticFluidRenderHandler.java:51)
	at me.steven.indrev.utils.FluidutilsKt.getTooltip(fluidutils.kt:136)
	at me.steven.indrev.gui.widgets.machines.WCustomBarKt$fluidTank$tank$1.addTooltip(WCustomBar.kt:118)
	at io.github.cottonmc.cotton.gui.widget.WWidget.renderTooltip(WWidget.java:351)
	at io.github.cottonmc.cotton.gui.client.CottonInventoryScreen.method_25394(CottonInventoryScreen.java:267)
	at net.minecraft.class_757.method_3192(class_757.java:874)
	... 10 more

**Comment by Justsnoopy30** [comment]
Linked indrev issue: https://github.com/GabrielOlvH/Industrial-Revolution/issues/354

**Comment by kvverti** [comment]
This is because Industrial Revolution passes `null` as the fluid state argument
